#  █████▒▄▄▄       ██▓     ██▓     ▄▄▄▄    ▄▄▄       ▄████▄   ██ ▄█▀     ██████ ▓█████  ██▀███   ██▒   █▓▓█████  ██▀███
#▓██   ▒▒████▄    ▓██▒    ▓██▒    ▓█████▄ ▒████▄    ▒██▀ ▀█   ██▄█▒    ▒██    ▒ ▓█   ▀ ▓██ ▒ ██▒▓██░   █▒▓█   ▀ ▓██ ▒ ██▒
#▒████ ░▒██  ▀█▄  ▒██░    ▒██░    ▒██▒ ▄██▒██  ▀█▄  ▒▓█    ▄ ▓███▄░    ░ ▓██▄   ▒███   ▓██ ░▄█ ▒ ▓██  █▒░▒███   ▓██ ░▄█ ▒
#░▓█▒  ░░██▄▄▄▄██ ▒██░    ▒██░    ▒██░█▀  ░██▄▄▄▄██ ▒▓▓▄ ▄██▒▓██ █▄      ▒   ██▒▒▓█  ▄ ▒██▀▀█▄    ▒██ █░░▒▓█  ▄ ▒██▀▀█▄
#░▒█░    ▓█   ▓██▒░██████▒░██████▒░▓█  ▀█▓ ▓█   ▓██▒▒ ▓███▀ ░▒██▒ █▄   ▒██████▒▒░▒████▒░██▓ ▒██▒   ▒▀█░  ░▒████▒░██▓ ▒██▒
# ▒ ░    ▒▒   ▓▒█░░ ▒░▓  ░░ ▒░▓  ░░▒▓███▀▒ ▒▒   ▓▒█░░ ░▒ ▒  ░▒ ▒▒ ▓▒   ▒ ▒▓▒ ▒ ░░░ ▒░ ░░ ▒▓ ░▒▓░   ░ ▐░  ░░ ▒░ ░░ ▒▓ ░▒▓░
# ░       ▒   ▒▒ ░░ ░ ▒  ░░ ░ ▒  ░▒░▒   ░   ▒   ▒▒ ░  ░  ▒   ░ ░▒ ▒░   ░ ░▒  ░ ░ ░ ░  ░  ░▒ ░ ▒░   ░ ░░   ░ ░  ░  ░▒ ░ ▒░
# ░ ░     ░   ▒     ░ ░     ░ ░    ░    ░   ░   ▒   ░        ░ ░░ ░    ░  ░  ░     ░     ░░   ░      ░░     ░     ░░   ░
#             ░  ░    ░  ░    ░  ░ ░            ░  ░░ ░      ░  ░            ░     ░  ░   ░           ░     ░  ░   ░
#                                       ░           ░                                                ░
# Made by CandiesJar | Github: github.com/sasi2006166 | Discord: https://discord.gg/fmUc6g3x | Telegram: @CandiesJar

# IMPORTANT WARNING: Before reporting any issue on discord, read carefully the comments!
# Most features are still under working and are disabled.
# Thanks for understanding.

settings:

  # Only players with permission will be able to tab-complete the command.
  command_tab_complete: true

  # RECONNECT: Player will not be disconnected from the server, instead gets a title
  # that says "Reconnecting" with animated dots, if crashed server doesn't go again
  # online the plugin will automatically balance them tough lobbies.
  # NORMAL: Normal kick method, after a server crash the plugin will automatically
  # balance all your kicked players.
  # IMPORTANT: This option requires a proxy reboot.
  fallback_mode: DEFAULT

  # Reconnect section, it will ONLY work if fallback_mode is set to RECONNECT.
  # Customize things like delays and title mode, everything in seconds.
  auto_reconnect:
    # Tries before disconnecting or moving player to lobbies.
    max_tries: 5

    # Time before pinging the server during reconnect phase.
    # Don't put values under 1, they will NOT work.
    ping_delay: 10

    # This option will kick player(s) if the reconnect task fails.
    # I don't recommend using this if you don't want to lose players.
    disconnect: false

    # This option will trigger normal FallbackServer kicking procedure.
    # Sorting players in various lobbies.
    player_sort: true

    # Title can be customized into messages configuration.
    # Available in messages.yml
    title:
      enable: true
      # NORMAL: The normal animated title with dots
      # PULSE: A title that simulates the heartbeat
      # You can customize it in messages.yml
      mode: NORMAL # Disabled for now.

  # False: Only players with permission will be able to see main command output.
  # True: Players without permission will receive the output message of main command (limited).
  command_without_permission: true

  # As it says, enables updates checking.
  check_updates: true

  # In seconds, checks the lobby list every 5 seconds, recommended staying with default value.
  # On first start / reboot, let the plugin settle down for 5 seconds before start using fallback.
  task_period: 5

  # Checks if stats should be enabled -> https://bstats.org/plugin/bungeecord/FallbackServer/11817
  stats: true

  # True: the plugin will automatically choose best lobby when connecting and balance all players.
  # Warning: If the list contains one lobby the balancing will not work.
  # Currently, work-in-progress, disabled until stable release.
  join_balancing: false

  # Administrator will be notified which server goes down and the complete reason of shutdown.
  admin_notification: true

  # Enable if you want to block lobby commands in specified servers.
  # Example: A player needs to checked for hacks and tries to use /lobby command in a server dedicated for that.
  disabled_servers: true

  # Add here the servers with the command(s) you want to block.
  # You can block any command, not only lobby command.
  disabled_servers_list:
    hack_control:
      - lobby
      - hub
    hack_control_2:
      - lobby
      - hub

  # Example: If the kicked message contains this (those) words the player will NOT be kicked.
  blacklisted_words:
    - "ban"
    - "whitelist"
    - "full"

  # Add here your lobbies, those will be used as fallback.
  # Those servers will also be used for the /lobby command.
  fallback_list:
    - lobby1
    - lobby2
    - lobby3

  # If you want to use the /lobby command (with aliases).
  # Requires Proxy reboot for applying changes.
  lobby_command: true

  # Aliases for /lobby command, it's possible to remove the base /hub command too.
  lobby_command_aliases:
    - hub
    - lobby

  # True: Enable blacklist, (Player needs to log-in but the server goes down, the plugin will not enable fallback).
  server_blacklist: true

  # Add here the blacklisted servers, such as pre-lobbies with authentication plugins.
  server_blacklist_list:
    - testserver

sub_commands:

  # Enabled: true, will enable the selected sub-command.
  # Permission: permission required to use the sub-command.

  admin:
    permission: "fallback.admin"

  reload:
    permission: "fallback.admin.reload"

  add:
    enabled: true
    permission: "fallback.admin.add"

  remove:
    enabled: true
    permission: "fallback.admin.remove"

  set:
    enabled: true
    permission: "fallback.admin.set"

  status:
    enabled: true
    permission: "fallback.admin.status"

  update:
    enabled: true
    permission: "fallback.admin.update"